// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: proto/pdpb/playdough.proto

package pdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug bool `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
}

func (x *RequestCommon) Reset() {
	*x = RequestCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pdpb_playdough_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCommon) ProtoMessage() {}

func (x *RequestCommon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdpb_playdough_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCommon.ProtoReflect.Descriptor instead.
func (*RequestCommon) Descriptor() ([]byte, []int) {
	return file_proto_pdpb_playdough_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCommon) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type ResponseCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseCommon) Reset() {
	*x = ResponseCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pdpb_playdough_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCommon) ProtoMessage() {}

func (x *ResponseCommon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdpb_playdough_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCommon.ProtoReflect.Descriptor instead.
func (*ResponseCommon) Descriptor() ([]byte, []int) {
	return file_proto_pdpb_playdough_proto_rawDescGZIP(), []int{1}
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common   *RequestCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Username string         `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string         `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pdpb_playdough_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdpb_playdough_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_pdpb_playdough_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetCommon() *RequestCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *ResponseCommon `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pdpb_playdough_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pdpb_playdough_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_pdpb_playdough_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetCommon() *ResponseCommon {
	if x != nil {
		return x.Common
	}
	return nil
}

var File_proto_pdpb_playdough_proto protoreflect.FileDescriptor

var file_proto_pdpb_playdough_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x64, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x61,
	0x79, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6c,
	0x61, 0x79, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x62, 0x22, 0x25, 0x0a, 0x0d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65,
	0x62, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x4c, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x69, 0x6e, 0x61, 0x72, 0x76, 0x6b, 0x2f, 0x70, 0x6c,
	0x61, 0x79, 0x64, 0x6f, 0x75, 0x67, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x64,
	0x70, 0x62, 0x3b, 0x70, 0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pdpb_playdough_proto_rawDescOnce sync.Once
	file_proto_pdpb_playdough_proto_rawDescData = file_proto_pdpb_playdough_proto_rawDesc
)

func file_proto_pdpb_playdough_proto_rawDescGZIP() []byte {
	file_proto_pdpb_playdough_proto_rawDescOnce.Do(func() {
		file_proto_pdpb_playdough_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pdpb_playdough_proto_rawDescData)
	})
	return file_proto_pdpb_playdough_proto_rawDescData
}

var file_proto_pdpb_playdough_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pdpb_playdough_proto_goTypes = []any{
	(*RequestCommon)(nil),         // 0: playdoughpb.RequestCommon
	(*ResponseCommon)(nil),        // 1: playdoughpb.ResponseCommon
	(*CreateAccountRequest)(nil),  // 2: playdoughpb.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 3: playdoughpb.CreateAccountResponse
}
var file_proto_pdpb_playdough_proto_depIdxs = []int32{
	0, // 0: playdoughpb.CreateAccountRequest.common:type_name -> playdoughpb.RequestCommon
	1, // 1: playdoughpb.CreateAccountResponse.common:type_name -> playdoughpb.ResponseCommon
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pdpb_playdough_proto_init() }
func file_proto_pdpb_playdough_proto_init() {
	if File_proto_pdpb_playdough_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pdpb_playdough_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pdpb_playdough_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pdpb_playdough_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pdpb_playdough_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pdpb_playdough_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pdpb_playdough_proto_goTypes,
		DependencyIndexes: file_proto_pdpb_playdough_proto_depIdxs,
		MessageInfos:      file_proto_pdpb_playdough_proto_msgTypes,
	}.Build()
	File_proto_pdpb_playdough_proto = out.File
	file_proto_pdpb_playdough_proto_rawDesc = nil
	file_proto_pdpb_playdough_proto_goTypes = nil
	file_proto_pdpb_playdough_proto_depIdxs = nil
}
